name: ContinuousIntegration

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

  # homolog-check:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: homolog
  #     url: 'your-application-here.com'
  #   needs: build
  #   steps:
  #     - name: Run hey there
  #       run: echo "Hey, there!"