name: Versioning Container

on:
  push:
    branches: [feature/docker]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Print Commit HASH
        run: echo ${GITHUB_SHA::8}
      
      - name: Opa
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: felipeleonardo/flask-app
          tags: $(shell git log -1 --format=%h)
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}