name: Versioning Container

on:
  push:
    branches: [gcp/*]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: is GCP
        if: github.ref == 'refs/heads/gcp/*'
        run: echo "Eu sou GCP"
      
      - name: is AWS
        if: github.ref == 'refs/heads/aws/*'
        run: echo "Eu sou AWS"