name: Versioning Container
'on':
  push:
    branches:
      - gcp/*
jobs:
  junior_push:
    runs-on: ubuntu-latest
    steps:
      - name: Run hey there
        run: echo "Hey, there!"
  gcp-check:
    runs-on: ubuntu-latest
    environment:
      name: gcp_cloud
      url: 'https://cloud.google.com'
    needs: junior_push
    steps:
      - name: Senior check
        run: 'echo "Ok, aceito"'
  run_image:
    runs-on: ubuntu-latest
    needs: gcp-check
    steps:
      - name: Repository Checkout again
        uses: actions/checkout@v2
      
