name: Versioning Container

on:
  push:
    branches: [feature/docker]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Print Commit HASH
        run: echo $(shell git log -1 --format=%h)
      
      - name: Opa
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: felipeleonardo/flask-app
          #tags: ${GITHUB_SHA::8}
          tags: $(echo ${GITHUB_SHA} | cut -c1-8)
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}